using System;

namespace DebugNET.PInvoke {
    [Flags]
    internal enum LoadLibraryFlags : uint {
        None = 0,
        DONT_RESOLVE_DLL_REFERENCES = 0x01,
        LOAD_LIBRARY_AS_DATAFILE = 0x02,
        LOAD_WITH_ALTERED_SEARCH_PATH = 0x08,
        LOAD_IGNORE_CODE_AUTHZ_LEVEL = 0x10,
        LOAD_LIBRARY_AS_IMAGE_RESOURCE = 0x20,
        LOAD_LIBRARY_AS_DATAFILE_EXCLUSIVE = 0x40,
        LOAD_LIBRARY_SEARCH_DLL_LOAD_DIR = 0x0100,
        LOAD_LIBRARY_SEARCH_APPLICATION_DIR = 0x0200,
        LOAD_LIBRARY_SEARCH_USER_DIRS = 0x0400,
        LOAD_LIBRARY_SEARCH_SYSTEM32 = 0x0800,
        LOAD_LIBRARY_SEARCH_DEFAULT_DIRS = 0x1000
    }
}
